name: Generate Snake Animation 🐍

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Generate the snake SVG based on contributions
      - name: Generate snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: adityapatil343  # Replace with your GitHub username
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Step 2: Push generated files to the repository
      - name: Push generated files
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Generated snake animation"
          add: "dist/*.svg"
